language: ruby
rvm:
- jruby-9.0.4.0
- 2.3.0
jdk: openjdk7
sudo: false
env:
  global:
  - PG_DISABLE_SSL='1'
cache: bundler
services:
  - redis
  - rabbitmq
  - postgresql
before_script:
  - createdb -U postgres travis_logs_test
  - cp config/travis.example.yml config/travis.yml
  - bundle exec rake db:migrate
script: bundle exec rspec spec
